### ISSUE TITLE
Visibility issues for actionTargetTemplate and eventSourceTemplate

### ISSUE THREAD

**Issue by Prevole** [SoftEng-HEIGVD/iflux-server-node#15]
It seems that the queries used to retrieve the templates does not take care of the scoping depending the way templates are retrieved.

**Comment by Prevole** [comment]
Private event source template created :

```
{
  "id": 4,
  "name": "novaserver",
  "public": false,
  "organizationId": 5
}
```

`GET eventSourceTemplates/4`

--> Possible to retrieve event source tempalte

`GET eventSourceTemplates/organizationId=5`

--> Possible to retrieve event source template

`GET eventSourceTemplates`

-> Event source template **does not** appear on the collection

User used is part of the organization.

**Comment by Prevole** [comment]
In fact, according to the API doc, when no args is provided to `GET eventSourceTemplates`, it will return **all public** eventSourceTemplates that a use can view. Only the public `eventSourceTemplates` will be retrieved.

Check the API Doc to get more info on the way to retrieve data. If you want to retrieve all the `eventSourceTemplates` from the organizations where he is member of, then use the `GET eventSourceTemplates?allOrganizations`.

Currently, there is no possibility to get the `public` and `private` `eventSourceTemplates` that a user can access across all the system.

**Comment by Prevole** [comment]
It should be possible to retrieve all the templates that a user can have access in one request. Therefore, it should be enhanced.

**Comment by Prevole** [comment]
In fact, the eventTypes and actionTypes are also concerned and will be improved too.

**Comment by jonesbusy** [comment]
Agreed.
