### ISSUE TITLE
Scoping issue for event source template

### ISSUE THREAD

**Issue by jonesbusy** [SoftEng-HEIGVD/iflux-server-node#16]
Private event source template created :

```
{
  "id": 4,
  "name": "novaserver",
  "public": false,
  "organizationId": 5
}
```

`GET eventSourceTemplates/4`

--> Possible to retrieve event source tempalte

`GET eventSourceTemplates/organizationId=5`

--> Possible to retrieve event source template

`GET eventSourceTemplates`

-> Event source template **does not** appear on the collection

User used is part of the organization.

**Comment by Prevole** [comment]
See #15
